language: python
python:
  - "3.6.5"

services:
  - postgresql

env:
  - DJANGO=2.1.7

before_install:
  - export DJANGO_SETTINGS_MODULE=hotel_api.settings.testing
  - export PYTHONPATH=$HOME/builds/Celoka/hotel_system

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE hotel_system_test;" -U postgres

script:
  - sh ./build.sh
  - coveralls
